import Head from "next/head";
import { Button } from '@chakra-ui/react'

import { Stage } from "@pixi/react";
import DraggableSprites from "@/components/DraggableSprites";
import ListOfSprites from "@/components/ListOfSprites";

import { Flex, Heading, Text } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Zen Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Flex margin="3% 0" justify="space-evenly">
        </Flex>
        <Flex direction="row" justify="space-around" align="center">
        <Flex direction="column" justify="space-around" align="center">
        <Text color="black" marginBlockEnd={3}>GARDEN</Text>

          <Stage options={{ backgroundColor: "#e0d9c9" }}>
            <DraggableSprites />
          </Stage>
          <Button >Save </Button></Flex>
          <ListOfSprites />
        </Flex>
      
      </main>
    </>
  );
}
